// <auto-generated />
namespace EmpMan.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedatatypeonTrialResultcolumnonEmpstable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedatatypeonTrialResultcolumnonEmpstable));
        
        string IMigrationMetadata.Id
        {
            get { return "201708091034038_change datatype on TrialResult column on Emps table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
