// <auto-generated />
namespace EmpMan.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Changemasterdataandempstablecolumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changemasterdataandempstablecolumns));
        
        string IMigrationMetadata.Id
        {
            get { return "201708020849372_Change master data and emps table columns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
