// <auto-generated />
namespace EmpMan.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addcolumnstorecruitmenttable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addcolumnstorecruitmenttable));
        
        string IMigrationMetadata.Id
        {
            get { return "201708150345408_Add columns to recruitment table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
