namespace EmpMan.Data.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class EmpandEmpDetailWorktableedit : DbMigration
    {
        public override void Up()
        {
            DropIndex("dbo.EmpDetailWorks", "ix_EmpDetailWork_Emp_StartDate_EndData_WorkTypeID");
            RenameColumn(table: "dbo.EmpDetailWorks", name: "WorkTypeID", newName: "PositionID");
            AddColumn("dbo.Emps", "JapaneseLevelMasterID", c => c.Int());
            AddColumn("dbo.Emps", "JapaneseLevelMasterDetailID", c => c.Int());
            AddColumn("dbo.Emps", "BusinessAllowanceLevelMasterID", c => c.Int());
            AddColumn("dbo.Emps", "BusinessAllowanceLevelMasterDetailID", c => c.Int());
            AddColumn("dbo.Emps", "RoomWithInternetAllowanceLevelMasterID", c => c.Int());
            AddColumn("dbo.Emps", "RoomWithInternetAllowanceLevelMasterDetailID", c => c.Int());
            AddColumn("dbo.Emps", "RoomNoInternetAllowanceLevelMasterID", c => c.Int());
            AddColumn("dbo.Emps", "RoomNoInternetAllowanceLevelMasterDetailID", c => c.Int());
            AddColumn("dbo.Emps", "BseAllowanceLevelMasterID", c => c.Int());
            AddColumn("dbo.Emps", "BseAllowanceLevelMasterDetailID", c => c.Int());
            AddColumn("dbo.EmpDetailWorks", "CompanyID", c => c.Int());
            AddColumn("dbo.EmpDetailWorks", "DeptID", c => c.Int());
            AddColumn("dbo.EmpDetailWorks", "TeamID", c => c.Int());
            AddColumn("dbo.EmpDetailWorks", "EmpTypeMasterID", c => c.Int());
            AddColumn("dbo.EmpDetailWorks", "EmpTypeMasterDetailID", c => c.Int());
            AddColumn("dbo.EmpDetailWorks", "JapaneseLevelMasterID", c => c.Int());
            AddColumn("dbo.EmpDetailWorks", "JapaneseLevelMasterDetailID", c => c.Int());
            AddColumn("dbo.EmpDetailWorks", "BusinessAllowanceLevelMasterID", c => c.Int());
            AddColumn("dbo.EmpDetailWorks", "BusinessAllowanceLevelMasterDetailID", c => c.Int());
            AddColumn("dbo.EmpDetailWorks", "RoomWithInternetAllowanceLevelMasterID", c => c.Int());
            AddColumn("dbo.EmpDetailWorks", "RoomWithInternetAllowanceLevelMasterDetailID", c => c.Int());
            AddColumn("dbo.EmpDetailWorks", "RoomNoInternetAllowanceLevelMasterID", c => c.Int());
            AddColumn("dbo.EmpDetailWorks", "RoomNoInternetAllowanceLevelMasterDetailID", c => c.Int());
            AddColumn("dbo.EmpDetailWorks", "BseAllowanceLevelMasterID", c => c.Int());
            AddColumn("dbo.EmpDetailWorks", "BseAllowanceLevelMasterDetailID", c => c.Int());
            AddColumn("dbo.EmpDetailWorks", "CollectMasterID", c => c.Int());
            AddColumn("dbo.EmpDetailWorks", "CollectMasterDetailID", c => c.Int());
            AddColumn("dbo.EmpDetailWorks", "EducationLevelMasterID", c => c.Int());
            AddColumn("dbo.EmpDetailWorks", "EducationLevelMasterDetailID", c => c.Int());
            AddColumn("dbo.EmpDetailWorks", "ContractTypeMasterID", c => c.Int());
            AddColumn("dbo.EmpDetailWorks", "ContractTypeMasterDetailID", c => c.Int());
            AlterColumn("dbo.EmpDetailWorks", "PositionID", c => c.Int());
            CreateIndex("dbo.Emps", "CurrentCompanyID");
            CreateIndex("dbo.Emps", new[] { "JapaneseLevelMasterID", "JapaneseLevelMasterDetailID" });
            CreateIndex("dbo.Emps", new[] { "BusinessAllowanceLevelMasterID", "BusinessAllowanceLevelMasterDetailID" });
            CreateIndex("dbo.Emps", new[] { "RoomWithInternetAllowanceLevelMasterID", "RoomWithInternetAllowanceLevelMasterDetailID" });
            CreateIndex("dbo.Emps", new[] { "RoomNoInternetAllowanceLevelMasterID", "RoomNoInternetAllowanceLevelMasterDetailID" });
            CreateIndex("dbo.Emps", new[] { "BseAllowanceLevelMasterID", "BseAllowanceLevelMasterDetailID" });
            CreateIndex("dbo.EmpDetailWorks", new[] { "EmpID", "StartDate", "EndDate" }, unique: true, name: "ix_EmpDetailWork_Emp_StartDate_EndData_WorkTypeID");
            CreateIndex("dbo.EmpDetailWorks", "CompanyID");
            CreateIndex("dbo.EmpDetailWorks", "DeptID");
            CreateIndex("dbo.EmpDetailWorks", "TeamID");
            CreateIndex("dbo.EmpDetailWorks", "PositionID");
            CreateIndex("dbo.EmpDetailWorks", new[] { "EmpTypeMasterID", "EmpTypeMasterDetailID" });
            CreateIndex("dbo.EmpDetailWorks", new[] { "JapaneseLevelMasterID", "JapaneseLevelMasterDetailID" });
            CreateIndex("dbo.EmpDetailWorks", new[] { "BusinessAllowanceLevelMasterID", "BusinessAllowanceLevelMasterDetailID" });
            CreateIndex("dbo.EmpDetailWorks", new[] { "RoomWithInternetAllowanceLevelMasterID", "RoomWithInternetAllowanceLevelMasterDetailID" });
            CreateIndex("dbo.EmpDetailWorks", new[] { "RoomNoInternetAllowanceLevelMasterID", "RoomNoInternetAllowanceLevelMasterDetailID" });
            CreateIndex("dbo.EmpDetailWorks", new[] { "BseAllowanceLevelMasterID", "BseAllowanceLevelMasterDetailID" });
            CreateIndex("dbo.EmpDetailWorks", new[] { "CollectMasterID", "CollectMasterDetailID" });
            CreateIndex("dbo.EmpDetailWorks", new[] { "EducationLevelMasterID", "EducationLevelMasterDetailID" });
            CreateIndex("dbo.EmpDetailWorks", new[] { "ContractTypeMasterID", "ContractTypeMasterDetailID" });
            AddForeignKey("dbo.Emps", new[] { "BseAllowanceLevelMasterID", "BseAllowanceLevelMasterDetailID" }, "dbo.MasterDetails", new[] { "MasterID", "MasterDetailCode" });
            AddForeignKey("dbo.Emps", new[] { "BusinessAllowanceLevelMasterID", "BusinessAllowanceLevelMasterDetailID" }, "dbo.MasterDetails", new[] { "MasterID", "MasterDetailCode" });
            AddForeignKey("dbo.Emps", "CurrentCompanyID", "dbo.Depts", "ID");
            AddForeignKey("dbo.EmpDetailWorks", new[] { "BseAllowanceLevelMasterID", "BseAllowanceLevelMasterDetailID" }, "dbo.MasterDetails", new[] { "MasterID", "MasterDetailCode" });
            AddForeignKey("dbo.EmpDetailWorks", new[] { "BusinessAllowanceLevelMasterID", "BusinessAllowanceLevelMasterDetailID" }, "dbo.MasterDetails", new[] { "MasterID", "MasterDetailCode" });
            AddForeignKey("dbo.EmpDetailWorks", new[] { "CollectMasterID", "CollectMasterDetailID" }, "dbo.MasterDetails", new[] { "MasterID", "MasterDetailCode" });
            AddForeignKey("dbo.EmpDetailWorks", "CompanyID", "dbo.Depts", "ID");
            AddForeignKey("dbo.EmpDetailWorks", new[] { "ContractTypeMasterID", "ContractTypeMasterDetailID" }, "dbo.MasterDetails", new[] { "MasterID", "MasterDetailCode" });
            AddForeignKey("dbo.EmpDetailWorks", "DeptID", "dbo.Depts", "ID");
            AddForeignKey("dbo.EmpDetailWorks", new[] { "EducationLevelMasterID", "EducationLevelMasterDetailID" }, "dbo.MasterDetails", new[] { "MasterID", "MasterDetailCode" });
            AddForeignKey("dbo.EmpDetailWorks", new[] { "EmpTypeMasterID", "EmpTypeMasterDetailID" }, "dbo.MasterDetails", new[] { "MasterID", "MasterDetailCode" });
            AddForeignKey("dbo.EmpDetailWorks", new[] { "JapaneseLevelMasterID", "JapaneseLevelMasterDetailID" }, "dbo.MasterDetails", new[] { "MasterID", "MasterDetailCode" });
            AddForeignKey("dbo.EmpDetailWorks", new[] { "RoomNoInternetAllowanceLevelMasterID", "RoomNoInternetAllowanceLevelMasterDetailID" }, "dbo.MasterDetails", new[] { "MasterID", "MasterDetailCode" });
            AddForeignKey("dbo.EmpDetailWorks", new[] { "RoomWithInternetAllowanceLevelMasterID", "RoomWithInternetAllowanceLevelMasterDetailID" }, "dbo.MasterDetails", new[] { "MasterID", "MasterDetailCode" });
            AddForeignKey("dbo.EmpDetailWorks", "TeamID", "dbo.Teams", "ID");
            AddForeignKey("dbo.Emps", new[] { "JapaneseLevelMasterID", "JapaneseLevelMasterDetailID" }, "dbo.MasterDetails", new[] { "MasterID", "MasterDetailCode" });
            AddForeignKey("dbo.Emps", new[] { "RoomNoInternetAllowanceLevelMasterID", "RoomNoInternetAllowanceLevelMasterDetailID" }, "dbo.MasterDetails", new[] { "MasterID", "MasterDetailCode" });
            AddForeignKey("dbo.Emps", new[] { "RoomWithInternetAllowanceLevelMasterID", "RoomWithInternetAllowanceLevelMasterDetailID" }, "dbo.MasterDetails", new[] { "MasterID", "MasterDetailCode" });
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.Emps", new[] { "RoomWithInternetAllowanceLevelMasterID", "RoomWithInternetAllowanceLevelMasterDetailID" }, "dbo.MasterDetails");
            DropForeignKey("dbo.Emps", new[] { "RoomNoInternetAllowanceLevelMasterID", "RoomNoInternetAllowanceLevelMasterDetailID" }, "dbo.MasterDetails");
            DropForeignKey("dbo.Emps", new[] { "JapaneseLevelMasterID", "JapaneseLevelMasterDetailID" }, "dbo.MasterDetails");
            DropForeignKey("dbo.EmpDetailWorks", "TeamID", "dbo.Teams");
            DropForeignKey("dbo.EmpDetailWorks", new[] { "RoomWithInternetAllowanceLevelMasterID", "RoomWithInternetAllowanceLevelMasterDetailID" }, "dbo.MasterDetails");
            DropForeignKey("dbo.EmpDetailWorks", new[] { "RoomNoInternetAllowanceLevelMasterID", "RoomNoInternetAllowanceLevelMasterDetailID" }, "dbo.MasterDetails");
            DropForeignKey("dbo.EmpDetailWorks", new[] { "JapaneseLevelMasterID", "JapaneseLevelMasterDetailID" }, "dbo.MasterDetails");
            DropForeignKey("dbo.EmpDetailWorks", new[] { "EmpTypeMasterID", "EmpTypeMasterDetailID" }, "dbo.MasterDetails");
            DropForeignKey("dbo.EmpDetailWorks", new[] { "EducationLevelMasterID", "EducationLevelMasterDetailID" }, "dbo.MasterDetails");
            DropForeignKey("dbo.EmpDetailWorks", "DeptID", "dbo.Depts");
            DropForeignKey("dbo.EmpDetailWorks", new[] { "ContractTypeMasterID", "ContractTypeMasterDetailID" }, "dbo.MasterDetails");
            DropForeignKey("dbo.EmpDetailWorks", "CompanyID", "dbo.Depts");
            DropForeignKey("dbo.EmpDetailWorks", new[] { "CollectMasterID", "CollectMasterDetailID" }, "dbo.MasterDetails");
            DropForeignKey("dbo.EmpDetailWorks", new[] { "BusinessAllowanceLevelMasterID", "BusinessAllowanceLevelMasterDetailID" }, "dbo.MasterDetails");
            DropForeignKey("dbo.EmpDetailWorks", new[] { "BseAllowanceLevelMasterID", "BseAllowanceLevelMasterDetailID" }, "dbo.MasterDetails");
            DropForeignKey("dbo.Emps", "CurrentCompanyID", "dbo.Depts");
            DropForeignKey("dbo.Emps", new[] { "BusinessAllowanceLevelMasterID", "BusinessAllowanceLevelMasterDetailID" }, "dbo.MasterDetails");
            DropForeignKey("dbo.Emps", new[] { "BseAllowanceLevelMasterID", "BseAllowanceLevelMasterDetailID" }, "dbo.MasterDetails");
            DropIndex("dbo.EmpDetailWorks", new[] { "ContractTypeMasterID", "ContractTypeMasterDetailID" });
            DropIndex("dbo.EmpDetailWorks", new[] { "EducationLevelMasterID", "EducationLevelMasterDetailID" });
            DropIndex("dbo.EmpDetailWorks", new[] { "CollectMasterID", "CollectMasterDetailID" });
            DropIndex("dbo.EmpDetailWorks", new[] { "BseAllowanceLevelMasterID", "BseAllowanceLevelMasterDetailID" });
            DropIndex("dbo.EmpDetailWorks", new[] { "RoomNoInternetAllowanceLevelMasterID", "RoomNoInternetAllowanceLevelMasterDetailID" });
            DropIndex("dbo.EmpDetailWorks", new[] { "RoomWithInternetAllowanceLevelMasterID", "RoomWithInternetAllowanceLevelMasterDetailID" });
            DropIndex("dbo.EmpDetailWorks", new[] { "BusinessAllowanceLevelMasterID", "BusinessAllowanceLevelMasterDetailID" });
            DropIndex("dbo.EmpDetailWorks", new[] { "JapaneseLevelMasterID", "JapaneseLevelMasterDetailID" });
            DropIndex("dbo.EmpDetailWorks", new[] { "EmpTypeMasterID", "EmpTypeMasterDetailID" });
            DropIndex("dbo.EmpDetailWorks", new[] { "PositionID" });
            DropIndex("dbo.EmpDetailWorks", new[] { "TeamID" });
            DropIndex("dbo.EmpDetailWorks", new[] { "DeptID" });
            DropIndex("dbo.EmpDetailWorks", new[] { "CompanyID" });
            DropIndex("dbo.EmpDetailWorks", "ix_EmpDetailWork_Emp_StartDate_EndData_WorkTypeID");
            DropIndex("dbo.Emps", new[] { "BseAllowanceLevelMasterID", "BseAllowanceLevelMasterDetailID" });
            DropIndex("dbo.Emps", new[] { "RoomNoInternetAllowanceLevelMasterID", "RoomNoInternetAllowanceLevelMasterDetailID" });
            DropIndex("dbo.Emps", new[] { "RoomWithInternetAllowanceLevelMasterID", "RoomWithInternetAllowanceLevelMasterDetailID" });
            DropIndex("dbo.Emps", new[] { "BusinessAllowanceLevelMasterID", "BusinessAllowanceLevelMasterDetailID" });
            DropIndex("dbo.Emps", new[] { "JapaneseLevelMasterID", "JapaneseLevelMasterDetailID" });
            DropIndex("dbo.Emps", new[] { "CurrentCompanyID" });
            AlterColumn("dbo.EmpDetailWorks", "PositionID", c => c.Int(nullable: false));
            DropColumn("dbo.EmpDetailWorks", "ContractTypeMasterDetailID");
            DropColumn("dbo.EmpDetailWorks", "ContractTypeMasterID");
            DropColumn("dbo.EmpDetailWorks", "EducationLevelMasterDetailID");
            DropColumn("dbo.EmpDetailWorks", "EducationLevelMasterID");
            DropColumn("dbo.EmpDetailWorks", "CollectMasterDetailID");
            DropColumn("dbo.EmpDetailWorks", "CollectMasterID");
            DropColumn("dbo.EmpDetailWorks", "BseAllowanceLevelMasterDetailID");
            DropColumn("dbo.EmpDetailWorks", "BseAllowanceLevelMasterID");
            DropColumn("dbo.EmpDetailWorks", "RoomNoInternetAllowanceLevelMasterDetailID");
            DropColumn("dbo.EmpDetailWorks", "RoomNoInternetAllowanceLevelMasterID");
            DropColumn("dbo.EmpDetailWorks", "RoomWithInternetAllowanceLevelMasterDetailID");
            DropColumn("dbo.EmpDetailWorks", "RoomWithInternetAllowanceLevelMasterID");
            DropColumn("dbo.EmpDetailWorks", "BusinessAllowanceLevelMasterDetailID");
            DropColumn("dbo.EmpDetailWorks", "BusinessAllowanceLevelMasterID");
            DropColumn("dbo.EmpDetailWorks", "JapaneseLevelMasterDetailID");
            DropColumn("dbo.EmpDetailWorks", "JapaneseLevelMasterID");
            DropColumn("dbo.EmpDetailWorks", "EmpTypeMasterDetailID");
            DropColumn("dbo.EmpDetailWorks", "EmpTypeMasterID");
            DropColumn("dbo.EmpDetailWorks", "TeamID");
            DropColumn("dbo.EmpDetailWorks", "DeptID");
            DropColumn("dbo.EmpDetailWorks", "CompanyID");
            DropColumn("dbo.Emps", "BseAllowanceLevelMasterDetailID");
            DropColumn("dbo.Emps", "BseAllowanceLevelMasterID");
            DropColumn("dbo.Emps", "RoomNoInternetAllowanceLevelMasterDetailID");
            DropColumn("dbo.Emps", "RoomNoInternetAllowanceLevelMasterID");
            DropColumn("dbo.Emps", "RoomWithInternetAllowanceLevelMasterDetailID");
            DropColumn("dbo.Emps", "RoomWithInternetAllowanceLevelMasterID");
            DropColumn("dbo.Emps", "BusinessAllowanceLevelMasterDetailID");
            DropColumn("dbo.Emps", "BusinessAllowanceLevelMasterID");
            DropColumn("dbo.Emps", "JapaneseLevelMasterDetailID");
            DropColumn("dbo.Emps", "JapaneseLevelMasterID");
            RenameColumn(table: "dbo.EmpDetailWorks", name: "PositionID", newName: "WorkTypeID");
            CreateIndex("dbo.EmpDetailWorks", new[] { "EmpID", "StartDate", "EndDate", "WorkTypeID" }, unique: true, name: "ix_EmpDetailWork_Emp_StartDate_EndData_WorkTypeID");
        }
    }
}
